<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoByCustomerIdResp.proto

namespace NetsvrProtocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，返回网关中的info
 *
 * Generated from protobuf message <code>netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdResp</code>
 */
class ConnInfoByCustomerIdResp extends \Google\Protobuf\Internal\Message
{
    /**
     *key是customerId,value是其在网关中存储的数据
     *
     * Generated from protobuf field <code>map<string, .netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItems> items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $items
     *          key是customerId,value是其在网关中存储的数据
     * }
     */
    public function __construct($data = NULL) {
        \NetsvrProtocol\GPBMetadata\ConnInfoByCustomerIdResp::initOnce();
        parent::__construct($data);
    }

    /**
     *key是customerId,value是其在网关中存储的数据
     *
     * Generated from protobuf field <code>map<string, .netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItems> items = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *key是customerId,value是其在网关中存储的数据
     *
     * Generated from protobuf field <code>map<string, .netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItems> items = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \NetsvrProtocol\ConnInfoByCustomerIdRespItems::class);
        $this->items = $arr;

        return $this;
    }

}

