<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoByCustomerIdReq.proto

namespace NetsvrProtocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，获取目标customerId在网关中存储的信息
 *
 * Generated from protobuf message <code>netsvr.connInfoByCustomerIdReq.ConnInfoByCustomerIdReq</code>
 */
class ConnInfoByCustomerIdReq extends \Google\Protobuf\Internal\Message
{
    /**
     *目标customerId
     *
     * Generated from protobuf field <code>repeated string customerIds = 1;</code>
     */
    private $customerIds;
    /**
     *是否获取session
     *
     * Generated from protobuf field <code>bool reqSession = 2;</code>
     */
    protected $reqSession = false;
    /**
     *是否获取uniqId
     *
     * Generated from protobuf field <code>bool reqUniqId = 3;</code>
     */
    protected $reqUniqId = false;
    /**
     *是否获取topic
     *
     * Generated from protobuf field <code>bool reqTopic = 4;</code>
     */
    protected $reqTopic = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $customerIds
     *          目标customerId
     *     @type bool $reqSession
     *          是否获取session
     *     @type bool $reqUniqId
     *          是否获取uniqId
     *     @type bool $reqTopic
     *          是否获取topic
     * }
     */
    public function __construct($data = NULL) {
        \NetsvrProtocol\GPBMetadata\ConnInfoByCustomerIdReq::initOnce();
        parent::__construct($data);
    }

    /**
     *目标customerId
     *
     * Generated from protobuf field <code>repeated string customerIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomerIds()
    {
        return $this->customerIds;
    }

    /**
     *目标customerId
     *
     * Generated from protobuf field <code>repeated string customerIds = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomerIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->customerIds = $arr;

        return $this;
    }

    /**
     *是否获取session
     *
     * Generated from protobuf field <code>bool reqSession = 2;</code>
     * @return bool
     */
    public function getReqSession()
    {
        return $this->reqSession;
    }

    /**
     *是否获取session
     *
     * Generated from protobuf field <code>bool reqSession = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReqSession($var)
    {
        GPBUtil::checkBool($var);
        $this->reqSession = $var;

        return $this;
    }

    /**
     *是否获取uniqId
     *
     * Generated from protobuf field <code>bool reqUniqId = 3;</code>
     * @return bool
     */
    public function getReqUniqId()
    {
        return $this->reqUniqId;
    }

    /**
     *是否获取uniqId
     *
     * Generated from protobuf field <code>bool reqUniqId = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setReqUniqId($var)
    {
        GPBUtil::checkBool($var);
        $this->reqUniqId = $var;

        return $this;
    }

    /**
     *是否获取topic
     *
     * Generated from protobuf field <code>bool reqTopic = 4;</code>
     * @return bool
     */
    public function getReqTopic()
    {
        return $this->reqTopic;
    }

    /**
     *是否获取topic
     *
     * Generated from protobuf field <code>bool reqTopic = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setReqTopic($var)
    {
        GPBUtil::checkBool($var);
        $this->reqTopic = $var;

        return $this;
    }

}

