<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpenResp.proto

namespace NetsvrProtocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *网关通过http协议转发客户端连接打开的信息到业务进程http接口，接口返回给网关的数据
 *
 * Generated from protobuf message <code>netsvr.connOpenResp.ConnOpenResp</code>
 */
class ConnOpenResp extends \Google\Protobuf\Internal\Message
{
    /**
     *是否允许连接
     *
     * Generated from protobuf field <code>bool allow = 1;</code>
     */
    protected $allow = false;
    /**
     *新的session，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>string newSession = 2;</code>
     */
    protected $newSession = '';
    /**
     *新的客户id，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>string newCustomerId = 3;</code>
     */
    protected $newCustomerId = '';
    /**
     *新的主题，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>repeated string newTopics = 4;</code>
     */
    private $newTopics;
    /**
     *需要发给客户的数据，传递了则转发给客户
     *
     * Generated from protobuf field <code>bytes data = 5;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $allow
     *          是否允许连接
     *     @type string $newSession
     *          新的session，传递了丢弃现有的，赋予新的
     *     @type string $newCustomerId
     *          新的客户id，传递了丢弃现有的，赋予新的
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $newTopics
     *          新的主题，传递了丢弃现有的，赋予新的
     *     @type string $data
     *          需要发给客户的数据，传递了则转发给客户
     * }
     */
    public function __construct($data = NULL) {
        \NetsvrProtocol\GPBMetadata\ConnOpenResp::initOnce();
        parent::__construct($data);
    }

    /**
     *是否允许连接
     *
     * Generated from protobuf field <code>bool allow = 1;</code>
     * @return bool
     */
    public function getAllow()
    {
        return $this->allow;
    }

    /**
     *是否允许连接
     *
     * Generated from protobuf field <code>bool allow = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllow($var)
    {
        GPBUtil::checkBool($var);
        $this->allow = $var;

        return $this;
    }

    /**
     *新的session，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>string newSession = 2;</code>
     * @return string
     */
    public function getNewSession()
    {
        return $this->newSession;
    }

    /**
     *新的session，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>string newSession = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->newSession = $var;

        return $this;
    }

    /**
     *新的客户id，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>string newCustomerId = 3;</code>
     * @return string
     */
    public function getNewCustomerId()
    {
        return $this->newCustomerId;
    }

    /**
     *新的客户id，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>string newCustomerId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNewCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->newCustomerId = $var;

        return $this;
    }

    /**
     *新的主题，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>repeated string newTopics = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewTopics()
    {
        return $this->newTopics;
    }

    /**
     *新的主题，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>repeated string newTopics = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->newTopics = $arr;

        return $this;
    }

    /**
     *需要发给客户的数据，传递了则转发给客户
     *
     * Generated from protobuf field <code>bytes data = 5;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *需要发给客户的数据，传递了则转发给客户
     *
     * Generated from protobuf field <code>bytes data = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

