<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastBulk.proto

namespace NetsvrProtocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，进行批量单播
 *网关必须实现以下三种处理：
 *1.当业务进程传递的uniqIds的uniqId数量与data的datum数量一致时，网关必须将同一下标的datum，发送给同一下标的uniqId
 *2.当业务进程传递的uniqIds的uniqId数量只有一个，data的datum数量是一个以上时，网关必须将所有的datum都发送给这个uniqId
 *3.除以上两种情况外，其它情况都丢弃不做处理
 *
 * Generated from protobuf message <code>netsvr.singleCastBulk.SingleCastBulk</code>
 */
class SingleCastBulk extends \Google\Protobuf\Internal\Message
{
    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     */
    private $uniqIds;
    /**
     *目标uniqId的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $uniqIds
     *          目标uniqId
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $data
     *          目标uniqId的数据
     * }
     */
    public function __construct($data = NULL) {
        \NetsvrProtocol\GPBMetadata\SingleCastBulk::initOnce();
        parent::__construct($data);
    }

    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqIds()
    {
        return $this->uniqIds;
    }

    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uniqIds = $arr;

        return $this;
    }

    /**
     *目标uniqId的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *目标uniqId的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->data = $arr;

        return $this;
    }

}

