<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdToUniqIdsListReq.proto

namespace NetsvrProtocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，获取网关中目标topic的customerId以及对应的uniqId列表
 *
 * Generated from protobuf message <code>netsvr.topicCustomerIdToUniqIdsListReq.TopicCustomerIdToUniqIdsListReq</code>
 */
class TopicCustomerIdToUniqIdsListReq extends \Google\Protobuf\Internal\Message
{
    /**
     *目标topic
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     */
    private $topics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          目标topic
     * }
     */
    public function __construct($data = NULL) {
        \NetsvrProtocol\GPBMetadata\TopicCustomerIdToUniqIdsListReq::initOnce();
        parent::__construct($data);
    }

    /**
     *目标topic
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *目标topic
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

}

