<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicPublishBulk.proto

namespace NetsvrProtocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，进行批量的主题发布信息
 *网关必须实现以下三种处理：
 *1.当业务进程传递的topics的topic数量与data的datum数量一致时，网关必须将同一下标的datum，发送给同一下标的topic
 *2.当业务进程传递的topics的topic数量只有一个，data的datum数量是一个以上时，网关必须将所有的datum都发送给这个topic
 *3.除以上两种情况外，其它情况都丢弃不做处理
 *
 * Generated from protobuf message <code>netsvr.topicPublishBulk.TopicPublishBulk</code>
 */
class TopicPublishBulk extends \Google\Protobuf\Internal\Message
{
    /**
     *目标主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     */
    private $topics;
    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          目标主题
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $data
     *          需要发给客户的数据
     * }
     */
    public function __construct($data = NULL) {
        \NetsvrProtocol\GPBMetadata\TopicPublishBulk::initOnce();
        parent::__construct($data);
    }

    /**
     *目标主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *目标主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->data = $arr;

        return $this;
    }

}

