<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto

namespace GPBMetadata;

class Broadcast
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
S
broadcast.protonetsvr.broadcast"
	Broadcast
data (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

