<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkOnlineResp.proto

namespace GPBMetadata;

class CheckOnlineResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
y
checkOnlineResp.protonetsvr.checkOnlineResp"3
CheckOnlineResp
ctxData (
uniqIds (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

