<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkOnlineReq.proto

namespace GPBMetadata;

class CheckOnlineReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‰
checkOnlineReq.protonetsvr.checkOnlineReq"E
CheckOnlineReq
	routerCmd (
ctxData (
uniqIds (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

