<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connClose.proto

namespace GPBMetadata;

class ConnClose
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
f
connClose.protonetsvr.connClose",
	ConnClose
uniqId (	
session (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

