<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpen.proto

namespace GPBMetadata;

class ConnOpen
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
connOpen.protonetsvr.connOpen"X
ConnOpen
uniqId (	
rawQuery (	
subProtocol (	
xForwardedFor (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

