<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infoDelete.proto

namespace GPBMetadata;

class InfoDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ÿ
infoDelete.protonetsvr.infoDelete"c

InfoDelete
uniqId (	
	delUniqId (

delSession (
delTopic (
data (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

