<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infoResp.proto

namespace GPBMetadata;

class InfoResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
„
infoResp.protonetsvr.infoResp"L
InfoResp
ctxData (
uniqId (	
session (	
topics (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

