<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitReq.proto

namespace GPBMetadata;

class LimitReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ê
limitReq.protonetsvr.limitReq"_
LimitReq
	routerCmd (
ctxData (/
items (2 .netsvr.limitReq.LimitUpdateItem"1
LimitUpdateItem
	workerIds (
num (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

