<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricsReq.proto

namespace GPBMetadata;

class MetricsReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
l
metricsReq.protonetsvr.metricsReq"0

MetricsReq
	routerCmd (
ctxData (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

