<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multicast.proto

namespace GPBMetadata;

class Multicast
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
d
multicast.protonetsvr.multicast"*
	Multicast
uniqIds (	
data (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

