<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto

namespace GPBMetadata;

class Register
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
n
register.protonetsvr.register"6
Register

Id (
ProcessCmdGoroutineNum (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

