<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicListReq.proto

namespace GPBMetadata;

class TopicListReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
r
topicListReq.protonetsvr.topicListReq"2
TopicListReq
	routerCmd (
ctxData (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

