<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdListResp.proto

namespace GPBMetadata;

class TopicUniqIdListResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
”
topicUniqIdListResp.protonetsvr.topicUniqIdListResp"F
TopicUniqIdListResp
ctxData (
topic (	
uniqIds (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

