<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto

namespace GPBMetadata;

class Transfer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
q
transfer.protonetsvr.transfer"9
Transfer
uniqId (	
session (	
data (BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

