<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uniqIdListResp.proto

namespace GPBMetadata;

class UniqIdListResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
v
uniqIdListResp.protonetsvr.uniqIdListResp"2
UniqIdListResp
ctxData (
uniqIds (	BZ	protocol/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

