<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto

namespace Netsvr;

use UnexpectedValueException;

/**
 *worker能够处理的指令，分为三块：1、worker单向转发给business的指令，2、business单向请求worker的指令，3、business请求worker，worker再响应business的指令
 *
 * Protobuf type <code>netsvr.router.Cmd</code>
 */
class Cmd
{
    /**
     *毫无意义的占位符，目的是避免枚举从零开始，另外把指令搞大一点的目的是避免和business的指令段冲突
     *
     * Generated from protobuf enum <code>Placeholder = 0;</code>
     */
    const Placeholder = 0;
    /**
     *--------------------------------worker单向转发给business的指令 开始--------------------------------
     *
     * Generated from protobuf enum <code>ConnOpen = 900001001;</code>
     */
    const ConnOpen = 900001001;
    /**
     *连接关闭
     *
     * Generated from protobuf enum <code>ConnClose = 900001002;</code>
     */
    const ConnClose = 900001002;
    /**
     *透传客户数据
     *
     * Generated from protobuf enum <code>Transfer = 900001003;</code>
     */
    const Transfer = 900001003;
    /**
     *--------------------------------business单向请求worker的指令，worker不会响应business 开始--------------------------------
     *
     * Generated from protobuf enum <code>ConnInfoUpdate = 900002001;</code>
     */
    const ConnInfoUpdate = 900002001;
    /**
     *删除连接的info信息
     *
     * Generated from protobuf enum <code>ConnInfoDelete = 900002002;</code>
     */
    const ConnInfoDelete = 900002002;
    /**
     *广播
     *
     * Generated from protobuf enum <code>Broadcast = 900002003;</code>
     */
    const Broadcast = 900002003;
    /**
     *组播
     *
     * Generated from protobuf enum <code>Multicast = 900002004;</code>
     */
    const Multicast = 900002004;
    /**
     *单播
     *
     * Generated from protobuf enum <code>SingleCast = 900002005;</code>
     */
    const SingleCast = 900002005;
    /**
     *批量单播
     *
     * Generated from protobuf enum <code>SingleCastBulk = 900002006;</code>
     */
    const SingleCastBulk = 900002006;
    /**
     *订阅
     *
     * Generated from protobuf enum <code>TopicSubscribe = 900002007;</code>
     */
    const TopicSubscribe = 900002007;
    /**
     *取消订阅
     *
     * Generated from protobuf enum <code>TopicUnsubscribe = 900002008;</code>
     */
    const TopicUnsubscribe = 900002008;
    /**
     *删除主题
     *
     * Generated from protobuf enum <code>TopicDelete = 900002009;</code>
     */
    const TopicDelete = 900002009;
    /**
     *发布
     *
     * Generated from protobuf enum <code>TopicPublish = 900002010;</code>
     */
    const TopicPublish = 900002010;
    /**
     *强制关闭某个连接
     *
     * Generated from protobuf enum <code>ForceOffline = 900002011;</code>
     */
    const ForceOffline = 900002011;
    /**
     *强制关闭某个空session值的连接
     *
     * Generated from protobuf enum <code>ForceOfflineGuest = 900002012;</code>
     */
    const ForceOfflineGuest = 900002012;
    /**
     *--------------------------------business请求worker的指令，worker会响应business 开始--------------------------------
     *
     * Generated from protobuf enum <code>Register = 900003001;</code>
     */
    const Register = 900003001;
    /**
     *取消注册，取消后不会再收到客户信息
     *
     * Generated from protobuf enum <code>Unregister = 900003002;</code>
     */
    const Unregister = 900003002;
    /**
     *判断uniqId是否在网关中
     *
     * Generated from protobuf enum <code>CheckOnline = 900003003;</code>
     */
    const CheckOnline = 900003003;
    /**
     *获取网关中全部的uniqId
     *
     * Generated from protobuf enum <code>UniqIdList = 900003004;</code>
     */
    const UniqIdList = 900003004;
    /**
     *获取网关中uniqId的数量
     *
     * Generated from protobuf enum <code>UniqIdCount = 900003005;</code>
     */
    const UniqIdCount = 900003005;
    /**
     *获取网关中的主题数量
     *
     * Generated from protobuf enum <code>TopicCount = 900003006;</code>
     */
    const TopicCount = 900003006;
    /**
     *获取网关中的主题
     *
     * Generated from protobuf enum <code>TopicList = 900003007;</code>
     */
    const TopicList = 900003007;
    /**
     *获取网关中某个主题包含的uniqId
     *
     * Generated from protobuf enum <code>TopicUniqIdList = 900003008;</code>
     */
    const TopicUniqIdList = 900003008;
    /**
     *获取网关中的主题包含的连接数
     *
     * Generated from protobuf enum <code>TopicUniqIdCount = 900003009;</code>
     */
    const TopicUniqIdCount = 900003009;
    /**
     *获取连接的信息
     *
     * Generated from protobuf enum <code>ConnInfo = 900003010;</code>
     */
    const ConnInfo = 900003010;
    /**
     *获取网关统计的服务状态
     *
     * Generated from protobuf enum <code>Metrics = 900003011;</code>
     */
    const Metrics = 900003011;
    /**
     *更新限流配置、获取网关中的限流配置的真实情况
     *
     * Generated from protobuf enum <code>Limit = 900003012;</code>
     */
    const Limit = 900003012;

    private static $valueToName = [
        self::Placeholder => 'Placeholder',
        self::ConnOpen => 'ConnOpen',
        self::ConnClose => 'ConnClose',
        self::Transfer => 'Transfer',
        self::ConnInfoUpdate => 'ConnInfoUpdate',
        self::ConnInfoDelete => 'ConnInfoDelete',
        self::Broadcast => 'Broadcast',
        self::Multicast => 'Multicast',
        self::SingleCast => 'SingleCast',
        self::SingleCastBulk => 'SingleCastBulk',
        self::TopicSubscribe => 'TopicSubscribe',
        self::TopicUnsubscribe => 'TopicUnsubscribe',
        self::TopicDelete => 'TopicDelete',
        self::TopicPublish => 'TopicPublish',
        self::ForceOffline => 'ForceOffline',
        self::ForceOfflineGuest => 'ForceOfflineGuest',
        self::Register => 'Register',
        self::Unregister => 'Unregister',
        self::CheckOnline => 'CheckOnline',
        self::UniqIdList => 'UniqIdList',
        self::UniqIdCount => 'UniqIdCount',
        self::TopicCount => 'TopicCount',
        self::TopicList => 'TopicList',
        self::TopicUniqIdList => 'TopicUniqIdList',
        self::TopicUniqIdCount => 'TopicUniqIdCount',
        self::ConnInfo => 'ConnInfo',
        self::Metrics => 'Metrics',
        self::Limit => 'Limit',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

