<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoUpdate.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *更新连接的info信息
 *
 * Generated from protobuf message <code>netsvr.connInfoUpdate.ConnInfoUpdate</code>
 */
class ConnInfoUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     */
    protected $uniqId = '';
    /**
     *新的uniqId，传递了则覆盖
     *
     * Generated from protobuf field <code>string newUniqId = 2;</code>
     */
    protected $newUniqId = '';
    /**
     *新的uniqId冲突的时候，需要转发给已经存在的连接的数据，有这个数据，则转发给该连接，并在3秒倒计时后强制关闭该连接，反之，立马关闭该连接
     *
     * Generated from protobuf field <code>bytes dataAsNewUniqIdExisted = 3;</code>
     */
    protected $dataAsNewUniqIdExisted = '';
    /**
     *新的session，传递了则覆盖
     *
     * Generated from protobuf field <code>string newSession = 4;</code>
     */
    protected $newSession = '';
    /**
     *新的主题，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>repeated string newTopics = 5;</code>
     */
    private $newTopics;
    /**
     *需要发给客户的数据，传递了则转发给客户
     *
     * Generated from protobuf field <code>bytes data = 6;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uniqId
     *          目标uniqId
     *     @type string $newUniqId
     *          新的uniqId，传递了则覆盖
     *     @type string $dataAsNewUniqIdExisted
     *          新的uniqId冲突的时候，需要转发给已经存在的连接的数据，有这个数据，则转发给该连接，并在3秒倒计时后强制关闭该连接，反之，立马关闭该连接
     *     @type string $newSession
     *          新的session，传递了则覆盖
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $newTopics
     *          新的主题，传递了丢弃现有的，赋予新的
     *     @type string $data
     *          需要发给客户的数据，传递了则转发给客户
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnInfoUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @return string
     */
    public function getUniqId()
    {
        return $this->uniqId;
    }

    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqId = $var;

        return $this;
    }

    /**
     *新的uniqId，传递了则覆盖
     *
     * Generated from protobuf field <code>string newUniqId = 2;</code>
     * @return string
     */
    public function getNewUniqId()
    {
        return $this->newUniqId;
    }

    /**
     *新的uniqId，传递了则覆盖
     *
     * Generated from protobuf field <code>string newUniqId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->newUniqId = $var;

        return $this;
    }

    /**
     *新的uniqId冲突的时候，需要转发给已经存在的连接的数据，有这个数据，则转发给该连接，并在3秒倒计时后强制关闭该连接，反之，立马关闭该连接
     *
     * Generated from protobuf field <code>bytes dataAsNewUniqIdExisted = 3;</code>
     * @return string
     */
    public function getDataAsNewUniqIdExisted()
    {
        return $this->dataAsNewUniqIdExisted;
    }

    /**
     *新的uniqId冲突的时候，需要转发给已经存在的连接的数据，有这个数据，则转发给该连接，并在3秒倒计时后强制关闭该连接，反之，立马关闭该连接
     *
     * Generated from protobuf field <code>bytes dataAsNewUniqIdExisted = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDataAsNewUniqIdExisted($var)
    {
        GPBUtil::checkString($var, False);
        $this->dataAsNewUniqIdExisted = $var;

        return $this;
    }

    /**
     *新的session，传递了则覆盖
     *
     * Generated from protobuf field <code>string newSession = 4;</code>
     * @return string
     */
    public function getNewSession()
    {
        return $this->newSession;
    }

    /**
     *新的session，传递了则覆盖
     *
     * Generated from protobuf field <code>string newSession = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNewSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->newSession = $var;

        return $this;
    }

    /**
     *新的主题，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>repeated string newTopics = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewTopics()
    {
        return $this->newTopics;
    }

    /**
     *新的主题，传递了丢弃现有的，赋予新的
     *
     * Generated from protobuf field <code>repeated string newTopics = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->newTopics = $arr;

        return $this;
    }

    /**
     *需要发给客户的数据，传递了则转发给客户
     *
     * Generated from protobuf field <code>bytes data = 6;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *需要发给客户的数据，传递了则转发给客户
     *
     * Generated from protobuf field <code>bytes data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

