<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpenCustomUniqIdTokenResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，返回uniqId、token
 *
 * Generated from protobuf message <code>netsvr.connOpenCustomUniqIdTokenResp.ConnOpenCustomUniqIdTokenResp</code>
 */
class ConnOpenCustomUniqIdTokenResp extends \Google\Protobuf\Internal\Message
{
    /**
     *网关生成的uniqId
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     */
    protected $uniqId = '';
    /**
     *网关生成的一次性token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uniqId
     *          网关生成的uniqId
     *     @type string $token
     *          网关生成的一次性token
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnOpenCustomUniqIdTokenResp::initOnce();
        parent::__construct($data);
    }

    /**
     *网关生成的uniqId
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @return string
     */
    public function getUniqId()
    {
        return $this->uniqId;
    }

    /**
     *网关生成的uniqId
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqId = $var;

        return $this;
    }

    /**
     *网关生成的一次性token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *网关生成的一次性token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

