<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoByCustomerIdResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItems</code>
 */
class ConnInfoByCustomerIdRespItems extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItem items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Netsvr\ConnInfoByCustomerIdRespItem>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnInfoByCustomerIdResp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItem items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItem items = 1;</code>
     * @param array<\Netsvr\ConnInfoByCustomerIdRespItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Netsvr\ConnInfoByCustomerIdRespItem::class);
        $this->items = $arr;

        return $this;
    }

}

