<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoReq.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，获取目标uniqId在网关中存储的信息
 *
 * Generated from protobuf message <code>netsvr.connInfoReq.ConnInfoReq</code>
 */
class ConnInfoReq extends \Google\Protobuf\Internal\Message
{
    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     */
    private $uniqIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $uniqIds
     *          目标uniqId
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnInfoReq::initOnce();
        parent::__construct($data);
    }

    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqIds()
    {
        return $this->uniqIds;
    }

    /**
     *目标uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uniqIds = $arr;

        return $this;
    }

}

