<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connClose.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker转发客户连接关闭的信息到business
 *
 * Generated from protobuf message <code>netsvr.connClose.ConnClose</code>
 */
class ConnClose extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uniqId = 1;</code>
     */
    protected $uniqId = '';
    /**
     * Generated from protobuf field <code>string session = 2;</code>
     */
    protected $session = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uniqId
     *     @type string $session
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnClose::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @return string
     */
    public function getUniqId()
    {
        return $this->uniqId;
    }

    /**
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session = 2;</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Generated from protobuf field <code>string session = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->session = $var;

        return $this;
    }

}

