<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpenCustomUniqIdTokenReq.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，设置连接打开时，传递自定义uniqId时的校验token
 *
 * Generated from protobuf message <code>netsvr.connOpenCustomUniqIdTokenReq.ConnOpenCustomUniqIdTokenReq</code>
 */
class ConnOpenCustomUniqIdTokenReq extends \Google\Protobuf\Internal\Message
{
    /**
     *token，随机性很强的字符串
     *
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     *网关在延时多少秒后删除token
     *
     * Generated from protobuf field <code>int32 delay = 2;</code>
     */
    protected $delay = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *          token，随机性很强的字符串
     *     @type int $delay
     *          网关在延时多少秒后删除token
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnOpenCustomUniqIdTokenReq::initOnce();
        parent::__construct($data);
    }

    /**
     *token，随机性很强的字符串
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *token，随机性很强的字符串
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *网关在延时多少秒后删除token
     *
     * Generated from protobuf field <code>int32 delay = 2;</code>
     * @return int
     */
    public function getDelay()
    {
        return $this->delay;
    }

    /**
     *网关在延时多少秒后删除token
     *
     * Generated from protobuf field <code>int32 delay = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->delay = $var;

        return $this;
    }

}

