<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connClose.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker转发客户连接关闭的信息到business
 *
 * Generated from protobuf message <code>netsvr.connClose.ConnClose</code>
 */
class ConnClose extends \Google\Protobuf\Internal\Message
{
    /**
     *客户在网关中的唯一id
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     */
    protected $uniqId = '';
    /**
     *客户在业务系统中的唯一id
     *
     * Generated from protobuf field <code>string customerId = 2;</code>
     */
    protected $customerId = '';
    /**
     *客户存储在网关中的数据
     *
     * Generated from protobuf field <code>string session = 3;</code>
     */
    protected $session = '';
    /**
     *客户订阅的主题
     *
     * Generated from protobuf field <code>repeated string topics = 4;</code>
     */
    private $topics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uniqId
     *          客户在网关中的唯一id
     *     @type string $customerId
     *          客户在业务系统中的唯一id
     *     @type string $session
     *          客户存储在网关中的数据
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          客户订阅的主题
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\ConnClose::initOnce();
        parent::__construct($data);
    }

    /**
     *客户在网关中的唯一id
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @return string
     */
    public function getUniqId()
    {
        return $this->uniqId;
    }

    /**
     *客户在网关中的唯一id
     *
     * Generated from protobuf field <code>string uniqId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqId = $var;

        return $this;
    }

    /**
     *客户在业务系统中的唯一id
     *
     * Generated from protobuf field <code>string customerId = 2;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     *客户在业务系统中的唯一id
     *
     * Generated from protobuf field <code>string customerId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

    /**
     *客户存储在网关中的数据
     *
     * Generated from protobuf field <code>string session = 3;</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     *客户存储在网关中的数据
     *
     * Generated from protobuf field <code>string session = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->session = $var;

        return $this;
    }

    /**
     *客户订阅的主题
     *
     * Generated from protobuf field <code>repeated string topics = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *客户订阅的主题
     *
     * Generated from protobuf field <code>repeated string topics = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

}

