<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Netsvr;

use UnexpectedValueException;

/**
 *网关的事件
 *
 * Protobuf type <code>netsvr.event.Event</code>
 */
class Event
{
    /**
     *毫无意义的占位符，目的是避免枚举从零开始
     *
     * Generated from protobuf enum <code>Placeholder = 0;</code>
     */
    const Placeholder = 0;
    /**
     *连接打开事件
     *
     * Generated from protobuf enum <code>OnOpen = 1;</code>
     */
    const OnOpen = 1;
    /**
     *连接关闭事件
     *
     * Generated from protobuf enum <code>OnClose = 2;</code>
     */
    const OnClose = 2;
    /**
     *连接收到消息事件
     *
     * Generated from protobuf enum <code>OnMessage = 4;</code>
     */
    const OnMessage = 4;

    private static $valueToName = [
        self::Placeholder => 'Placeholder',
        self::OnOpen => 'OnOpen',
        self::OnClose => 'OnClose',
        self::OnMessage => 'OnMessage',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

