<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infoResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，返回网关中的info
 *
 * Generated from protobuf message <code>netsvr.infoResp.InfoResp</code>
 */
class InfoResp extends \Google\Protobuf\Internal\Message
{
    /**
     *worker原样回传给business
     *
     * Generated from protobuf field <code>bytes ctxData = 1;</code>
     */
    protected $ctxData = '';
    /**
     *最新的uniqId
     *
     * Generated from protobuf field <code>string uniqId = 2;</code>
     */
    protected $uniqId = '';
    /**
     *最新的session
     *
     * Generated from protobuf field <code>string session = 3;</code>
     */
    protected $session = '';
    /**
     *最新的主题
     *
     * Generated from protobuf field <code>repeated string topics = 4;</code>
     */
    private $topics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ctxData
     *          worker原样回传给business
     *     @type string $uniqId
     *          最新的uniqId
     *     @type string $session
     *          最新的session
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          最新的主题
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\InfoResp::initOnce();
        parent::__construct($data);
    }

    /**
     *worker原样回传给business
     *
     * Generated from protobuf field <code>bytes ctxData = 1;</code>
     * @return string
     */
    public function getCtxData()
    {
        return $this->ctxData;
    }

    /**
     *worker原样回传给business
     *
     * Generated from protobuf field <code>bytes ctxData = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCtxData($var)
    {
        GPBUtil::checkString($var, False);
        $this->ctxData = $var;

        return $this;
    }

    /**
     *最新的uniqId
     *
     * Generated from protobuf field <code>string uniqId = 2;</code>
     * @return string
     */
    public function getUniqId()
    {
        return $this->uniqId;
    }

    /**
     *最新的uniqId
     *
     * Generated from protobuf field <code>string uniqId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqId = $var;

        return $this;
    }

    /**
     *最新的session
     *
     * Generated from protobuf field <code>string session = 3;</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     *最新的session
     *
     * Generated from protobuf field <code>string session = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->session = $var;

        return $this;
    }

    /**
     *最新的主题
     *
     * Generated from protobuf field <code>repeated string topics = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *最新的主题
     *
     * Generated from protobuf field <code>repeated string topics = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

}

