<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>netsvr.limitResp.LimitRespItem</code>
 */
class LimitRespItem extends \Google\Protobuf\Internal\Message
{
    /**
     *限流器的名字
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *限流器的并发设定
     *
     * Generated from protobuf field <code>int32 concurrency = 2;</code>
     */
    protected $concurrency = 0;
    /**
     *workerId集合
     *
     * Generated from protobuf field <code>repeated int32 workerIds = 3;</code>
     */
    private $workerIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          限流器的名字
     *     @type int $concurrency
     *          限流器的并发设定
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $workerIds
     *          workerId集合
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\LimitResp::initOnce();
        parent::__construct($data);
    }

    /**
     *限流器的名字
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *限流器的名字
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *限流器的并发设定
     *
     * Generated from protobuf field <code>int32 concurrency = 2;</code>
     * @return int
     */
    public function getConcurrency()
    {
        return $this->concurrency;
    }

    /**
     *限流器的并发设定
     *
     * Generated from protobuf field <code>int32 concurrency = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setConcurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->concurrency = $var;

        return $this;
    }

    /**
     *workerId集合
     *
     * Generated from protobuf field <code>repeated int32 workerIds = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWorkerIds()
    {
        return $this->workerIds;
    }

    /**
     *workerId集合
     *
     * Generated from protobuf field <code>repeated int32 workerIds = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWorkerIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->workerIds = $arr;

        return $this;
    }

}

