<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，返回网关中的限流配置的真实情况
 *
 * Generated from protobuf message <code>netsvr.limitResp.LimitResp</code>
 */
class LimitResp extends \Google\Protobuf\Internal\Message
{
    /**
     *worker会原样回传给business
     *
     * Generated from protobuf field <code>bytes ctxData = 1;</code>
     */
    protected $ctxData = '';
    /**
     *每个worker的配置情况
     *
     * Generated from protobuf field <code>repeated .netsvr.limitResp.LimitCountItem items = 2;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ctxData
     *          worker会原样回传给business
     *     @type array<\Netsvr\LimitCountItem>|\Google\Protobuf\Internal\RepeatedField $items
     *          每个worker的配置情况
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\LimitResp::initOnce();
        parent::__construct($data);
    }

    /**
     *worker会原样回传给business
     *
     * Generated from protobuf field <code>bytes ctxData = 1;</code>
     * @return string
     */
    public function getCtxData()
    {
        return $this->ctxData;
    }

    /**
     *worker会原样回传给business
     *
     * Generated from protobuf field <code>bytes ctxData = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCtxData($var)
    {
        GPBUtil::checkString($var, False);
        $this->ctxData = $var;

        return $this;
    }

    /**
     *每个worker的配置情况
     *
     * Generated from protobuf field <code>repeated .netsvr.limitResp.LimitCountItem items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *每个worker的配置情况
     *
     * Generated from protobuf field <code>repeated .netsvr.limitResp.LimitCountItem items = 2;</code>
     * @param array<\Netsvr\LimitCountItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Netsvr\LimitCountItem::class);
        $this->items = $arr;

        return $this;
    }

}

