<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，返回网关中的限流配置的真实情况
 *
 * Generated from protobuf message <code>netsvr.limitResp.LimitResp</code>
 */
class LimitResp extends \Google\Protobuf\Internal\Message
{
    /**
     *网关允许每秒转发多少个连接打开事件到business进程
     *
     * Generated from protobuf field <code>int32 onOpen = 1;</code>
     */
    protected $onOpen = 0;
    /**
     *网关允许每秒转发多少个消息到business进程
     *
     * Generated from protobuf field <code>int32 onMessage = 2;</code>
     */
    protected $onMessage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $onOpen
     *          网关允许每秒转发多少个连接打开事件到business进程
     *     @type int $onMessage
     *          网关允许每秒转发多少个消息到business进程
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\LimitResp::initOnce();
        parent::__construct($data);
    }

    /**
     *网关允许每秒转发多少个连接打开事件到business进程
     *
     * Generated from protobuf field <code>int32 onOpen = 1;</code>
     * @return int
     */
    public function getOnOpen()
    {
        return $this->onOpen;
    }

    /**
     *网关允许每秒转发多少个连接打开事件到business进程
     *
     * Generated from protobuf field <code>int32 onOpen = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOnOpen($var)
    {
        GPBUtil::checkInt32($var);
        $this->onOpen = $var;

        return $this;
    }

    /**
     *网关允许每秒转发多少个消息到business进程
     *
     * Generated from protobuf field <code>int32 onMessage = 2;</code>
     * @return int
     */
    public function getOnMessage()
    {
        return $this->onMessage;
    }

    /**
     *网关允许每秒转发多少个消息到business进程
     *
     * Generated from protobuf field <code>int32 onMessage = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOnMessage($var)
    {
        GPBUtil::checkInt32($var);
        $this->onMessage = $var;

        return $this;
    }

}

