<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，返回网关中的限流配置的真实情况
 *
 * Generated from protobuf message <code>netsvr.limitResp.LimitResp</code>
 */
class LimitResp extends \Google\Protobuf\Internal\Message
{
    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     */
    protected $serverId = 0;
    /**
     *网关服务中的限流器列表
     *
     * Generated from protobuf field <code>repeated .netsvr.limitResp.LimitRespItem items = 2;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $serverId
     *          网关唯一编号
     *     @type array<\Netsvr\LimitRespItem>|\Google\Protobuf\Internal\RepeatedField $items
     *          网关服务中的限流器列表
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\LimitResp::initOnce();
        parent::__construct($data);
    }

    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     * @return int
     */
    public function getServerId()
    {
        return $this->serverId;
    }

    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverId = $var;

        return $this;
    }

    /**
     *网关服务中的限流器列表
     *
     * Generated from protobuf field <code>repeated .netsvr.limitResp.LimitRespItem items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *网关服务中的限流器列表
     *
     * Generated from protobuf field <code>repeated .netsvr.limitResp.LimitRespItem items = 2;</code>
     * @param array<\Netsvr\LimitRespItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Netsvr\LimitRespItem::class);
        $this->items = $arr;

        return $this;
    }

}

