<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>netsvr.limitResp.LimitCountItem</code>
 */
class LimitCountItem extends \Google\Protobuf\Internal\Message
{
    /**
     *workerId集合
     *
     * Generated from protobuf field <code>repeated int32 workerIds = 1;</code>
     */
    private $workerIds;
    /**
     *限流大小
     *
     * Generated from protobuf field <code>int32 num = 2;</code>
     */
    protected $num = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $workerIds
     *          workerId集合
     *     @type int $num
     *          限流大小
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\LimitResp::initOnce();
        parent::__construct($data);
    }

    /**
     *workerId集合
     *
     * Generated from protobuf field <code>repeated int32 workerIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWorkerIds()
    {
        return $this->workerIds;
    }

    /**
     *workerId集合
     *
     * Generated from protobuf field <code>repeated int32 workerIds = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWorkerIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->workerIds = $arr;

        return $this;
    }

    /**
     *限流大小
     *
     * Generated from protobuf field <code>int32 num = 2;</code>
     * @return int
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     *限流大小
     *
     * Generated from protobuf field <code>int32 num = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->num = $var;

        return $this;
    }

}

