<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitReq.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *更新网关服务的限流配置，并返回网关中的最新的限流配置
 *如果设置一个无效的并发数，则会忽略这个配置
 *这个配置操作不是永久生效的，网关进程重启后就以netsvr.toml为准
 *
 * Generated from protobuf message <code>netsvr.limitReq.LimitReq</code>
 */
class LimitReq extends \Google\Protobuf\Internal\Message
{
    /**
     *网关允许每秒转发多少个连接打开事件到business进程
     *
     * Generated from protobuf field <code>int32 onOpen = 1;</code>
     */
    protected $onOpen = 0;
    /**
     *网关允许每秒转发多少个消息到business进程
     *
     * Generated from protobuf field <code>int32 onMessage = 2;</code>
     */
    protected $onMessage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $onOpen
     *          网关允许每秒转发多少个连接打开事件到business进程
     *     @type int $onMessage
     *          网关允许每秒转发多少个消息到business进程
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\LimitReq::initOnce();
        parent::__construct($data);
    }

    /**
     *网关允许每秒转发多少个连接打开事件到business进程
     *
     * Generated from protobuf field <code>int32 onOpen = 1;</code>
     * @return int
     */
    public function getOnOpen()
    {
        return $this->onOpen;
    }

    /**
     *网关允许每秒转发多少个连接打开事件到business进程
     *
     * Generated from protobuf field <code>int32 onOpen = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOnOpen($var)
    {
        GPBUtil::checkInt32($var);
        $this->onOpen = $var;

        return $this;
    }

    /**
     *网关允许每秒转发多少个消息到business进程
     *
     * Generated from protobuf field <code>int32 onMessage = 2;</code>
     * @return int
     */
    public function getOnMessage()
    {
        return $this->onMessage;
    }

    /**
     *网关允许每秒转发多少个消息到business进程
     *
     * Generated from protobuf field <code>int32 onMessage = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOnMessage($var)
    {
        GPBUtil::checkInt32($var);
        $this->onMessage = $var;

        return $this;
    }

}

