<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricsResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，返回网关统计的服务状态
 *
 * Generated from protobuf message <code>netsvr.metricsResp.MetricsResp</code>
 */
class MetricsResp extends \Google\Protobuf\Internal\Message
{
    /**
     *key是统计的项，value是统计结果
     *
     * Generated from protobuf field <code>map<int32, .netsvr.metricsResp.MetricsRespItem> items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $items
     *          key是统计的项，value是统计结果
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\MetricsResp::initOnce();
        parent::__construct($data);
    }

    /**
     *key是统计的项，value是统计结果
     *
     * Generated from protobuf field <code>map<int32, .netsvr.metricsResp.MetricsRespItem> items = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *key是统计的项，value是统计结果
     *
     * Generated from protobuf field <code>map<int32, .netsvr.metricsResp.MetricsRespItem> items = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Netsvr\MetricsRespItem::class);
        $this->items = $arr;

        return $this;
    }

}

