<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricsResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>netsvr.metricsResp.MetricsRespItem</code>
 */
class MetricsRespItem extends \Google\Protobuf\Internal\Message
{
    /**
     *统计的项
     *
     * Generated from protobuf field <code>int32 item = 1;</code>
     */
    protected $item = 0;
    /**
     *returns the count of events at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>int64 count = 2;</code>
     */
    protected $count = 0;
    /**
     * returns the meter's mean rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float meanRate = 3;</code>
     */
    protected $meanRate = 0.0;
    /**
     * Rate1 returns the one-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate1 = 5;</code>
     */
    protected $rate1 = 0.0;
    /**
     * Rate5 returns the five-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate5 = 7;</code>
     */
    protected $rate5 = 0.0;
    /**
     * Rate15 returns the fifteen-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate15 = 9;</code>
     */
    protected $rate15 = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $item
     *          统计的项
     *     @type int|string $count
     *          returns the count of events at the time the snapshot was taken.
     *     @type float $meanRate
     *           returns the meter's mean rate of events per second at the time the snapshot was taken.
     *     @type float $rate1
     *           Rate1 returns the one-minute moving average rate of events per second at the time the snapshot was taken.
     *     @type float $rate5
     *           Rate5 returns the five-minute moving average rate of events per second at the time the snapshot was taken.
     *     @type float $rate15
     *           Rate15 returns the fifteen-minute moving average rate of events per second at the time the snapshot was taken.
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\MetricsResp::initOnce();
        parent::__construct($data);
    }

    /**
     *统计的项
     *
     * Generated from protobuf field <code>int32 item = 1;</code>
     * @return int
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     *统计的项
     *
     * Generated from protobuf field <code>int32 item = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkInt32($var);
        $this->item = $var;

        return $this;
    }

    /**
     *returns the count of events at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>int64 count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *returns the count of events at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>int64 count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * returns the meter's mean rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float meanRate = 3;</code>
     * @return float
     */
    public function getMeanRate()
    {
        return $this->meanRate;
    }

    /**
     * returns the meter's mean rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float meanRate = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMeanRate($var)
    {
        GPBUtil::checkFloat($var);
        $this->meanRate = $var;

        return $this;
    }

    /**
     * Rate1 returns the one-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate1 = 5;</code>
     * @return float
     */
    public function getRate1()
    {
        return $this->rate1;
    }

    /**
     * Rate1 returns the one-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate1 = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setRate1($var)
    {
        GPBUtil::checkFloat($var);
        $this->rate1 = $var;

        return $this;
    }

    /**
     * Rate5 returns the five-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate5 = 7;</code>
     * @return float
     */
    public function getRate5()
    {
        return $this->rate5;
    }

    /**
     * Rate5 returns the five-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate5 = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setRate5($var)
    {
        GPBUtil::checkFloat($var);
        $this->rate5 = $var;

        return $this;
    }

    /**
     * Rate15 returns the fifteen-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate15 = 9;</code>
     * @return float
     */
    public function getRate15()
    {
        return $this->rate15;
    }

    /**
     * Rate15 returns the fifteen-minute moving average rate of events per second at the time the snapshot was taken.
     *
     * Generated from protobuf field <code>float rate15 = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setRate15($var)
    {
        GPBUtil::checkFloat($var);
        $this->rate15 = $var;

        return $this;
    }

}

