<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registerResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，注册自己，worker响应注册结果
 *
 * Generated from protobuf message <code>netsvr.registerResp.RegisterResp</code>
 */
class RegisterResp extends \Google\Protobuf\Internal\Message
{
    /**
     *注册结果：[1：成功，2：解析注册proto协议失败，3：workerId配置错误，溢出允许的范围，4：serverId配置错误，与网关配置的不一致，5：已经注册过，不允许重复发起注册请求]
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *          注册结果：[1：成功，2：解析注册proto协议失败，3：workerId配置错误，溢出允许的范围，4：serverId配置错误，与网关配置的不一致，5：已经注册过，不允许重复发起注册请求]
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\RegisterResp::initOnce();
        parent::__construct($data);
    }

    /**
     *注册结果：[1：成功，2：解析注册proto协议失败，3：workerId配置错误，溢出允许的范围，4：serverId配置错误，与网关配置的不一致，5：已经注册过，不允许重复发起注册请求]
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *注册结果：[1：成功，2：解析注册proto协议失败，3：workerId配置错误，溢出允许的范围，4：serverId配置错误，与网关配置的不一致，5：已经注册过，不允许重复发起注册请求]
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

