<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastByCustomerId.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，进行单播
 *
 * Generated from protobuf message <code>netsvr.singleCastByCustomerId.SingleCastByCustomerId</code>
 */
class SingleCastByCustomerId extends \Google\Protobuf\Internal\Message
{
    /**
     *目标customerId
     *
     * Generated from protobuf field <code>string customerId = 1;</code>
     */
    protected $customerId = '';
    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customerId
     *          目标customerId
     *     @type string $data
     *          需要发给客户的数据
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\SingleCastByCustomerId::initOnce();
        parent::__construct($data);
    }

    /**
     *目标customerId
     *
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     *目标customerId
     *
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

