<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastBulk.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，进行批量单播
 *
 * Generated from protobuf message <code>netsvr.singleCastBulk.SingleCastBulk</code>
 */
class SingleCastBulk extends \Google\Protobuf\Internal\Message
{
    /**
     *目标uniqId，有多少个uniqId，就有多少个data，下标是对应关系，worker端会循环uniqId，并用下标从data获取对应的数据
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     */
    private $uniqIds;
    /**
     *目标uniqId的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $uniqIds
     *          目标uniqId，有多少个uniqId，就有多少个data，下标是对应关系，worker端会循环uniqId，并用下标从data获取对应的数据
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $data
     *          目标uniqId的数据
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\SingleCastBulk::initOnce();
        parent::__construct($data);
    }

    /**
     *目标uniqId，有多少个uniqId，就有多少个data，下标是对应关系，worker端会循环uniqId，并用下标从data获取对应的数据
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqIds()
    {
        return $this->uniqIds;
    }

    /**
     *目标uniqId，有多少个uniqId，就有多少个data，下标是对应关系，worker端会循环uniqId，并用下标从data获取对应的数据
     *
     * Generated from protobuf field <code>repeated string uniqIds = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uniqIds = $arr;

        return $this;
    }

    /**
     *目标uniqId的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *目标uniqId的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->data = $arr;

        return $this;
    }

}

