<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdToUniqIdsListResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>netsvr.topicCustomerIdToUniqIdsListResp.TopicCustomerIdToUniqIdsListRespItem</code>
 */
class TopicCustomerIdToUniqIdsListRespItem extends \Google\Protobuf\Internal\Message
{
    /**
     *当前topic包含的customerId以及customerId对应的uniqId列表
     *
     * Generated from protobuf field <code>map<string, .netsvr.topicCustomerIdToUniqIdsListResp.CustomerIdToUniqIdsRespItem> items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $items
     *          当前topic包含的customerId以及customerId对应的uniqId列表
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\TopicCustomerIdToUniqIdsListResp::initOnce();
        parent::__construct($data);
    }

    /**
     *当前topic包含的customerId以及customerId对应的uniqId列表
     *
     * Generated from protobuf field <code>map<string, .netsvr.topicCustomerIdToUniqIdsListResp.CustomerIdToUniqIdsRespItem> items = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *当前topic包含的customerId以及customerId对应的uniqId列表
     *
     * Generated from protobuf field <code>map<string, .netsvr.topicCustomerIdToUniqIdsListResp.CustomerIdToUniqIdsRespItem> items = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Netsvr\CustomerIdToUniqIdsRespItem::class);
        $this->items = $arr;

        return $this;
    }

}

