<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicPublishBulk.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，进行批量的主题发布信息，多份不同的消息发布到多个不同的主题
 *举个场景：直播室消息需要人工审核，自己的消息无论是否审核通过都要显示在自己的消息列表，别人的消息只显示审核通过的。
 *用户发消息到你的服务器，大概处理逻辑就是：先写入数据库，然后再包装成一个客户端需要的消息格式，发布到对应直播室的主题；然后再包装成另外一个消息格式，发布到管理员审核消息的主题，给审核人员审核。
 *这里一份消息有两个格式，分别发布到直播室主题、审核直播室消息的主题，适合用该指令进行批量发布
 *
 * Generated from protobuf message <code>netsvr.topicPublishBulk.TopicPublishBulk</code>
 */
class TopicPublishBulk extends \Google\Protobuf\Internal\Message
{
    /**
     *目标主题，有多少个topic，就有多少个data，下标是对应关系，网关的worker服务器会循环uniqId，并用其下标从data获取对应的数据
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     */
    private $topics;
    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          目标主题，有多少个topic，就有多少个data，下标是对应关系，网关的worker服务器会循环uniqId，并用其下标从data获取对应的数据
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $data
     *          需要发给客户的数据
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\TopicPublishBulk::initOnce();
        parent::__construct($data);
    }

    /**
     *目标主题，有多少个topic，就有多少个data，下标是对应关系，网关的worker服务器会循环uniqId，并用其下标从data获取对应的数据
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *目标主题，有多少个topic，就有多少个data，下标是对应关系，网关的worker服务器会循环uniqId，并用其下标从data获取对应的数据
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *需要发给客户的数据
     *
     * Generated from protobuf field <code>repeated bytes data = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->data = $arr;

        return $this;
    }

}

