<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdCountResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，获取网关中目标topic的customerId
 *
 * Generated from protobuf message <code>netsvr.topicCustomerIdCountResp.TopicCustomerIdCountResp</code>
 */
class TopicCustomerIdCountResp extends \Google\Protobuf\Internal\Message
{
    /**
     *key是topic，value是该主题的customerId数量
     *如果请求的topic没找到，则items中不会有该topic
     *
     * Generated from protobuf field <code>map<string, int32> items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $items
     *          key是topic，value是该主题的customerId数量
     *          如果请求的topic没找到，则items中不会有该topic
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\TopicCustomerIdCountResp::initOnce();
        parent::__construct($data);
    }

    /**
     *key是topic，value是该主题的customerId数量
     *如果请求的topic没找到，则items中不会有该topic
     *
     * Generated from protobuf field <code>map<string, int32> items = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *key是topic，value是该主题的customerId数量
     *如果请求的topic没找到，则items中不会有该topic
     *
     * Generated from protobuf field <code>map<string, int32> items = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->items = $arr;

        return $this;
    }

}

