<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicDelete.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，进行删除主题操作
 *
 * Generated from protobuf message <code>netsvr.topicDelete.TopicDelete</code>
 */
class TopicDelete extends \Google\Protobuf\Internal\Message
{
    /**
     *需要删除的主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     */
    private $topics;
    /**
     *删除主题后，需要发给客户的数据，如果没有，可以不传
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          需要删除的主题
     *     @type string $data
     *          删除主题后，需要发给客户的数据，如果没有，可以不传
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\TopicDelete::initOnce();
        parent::__construct($data);
    }

    /**
     *需要删除的主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *需要删除的主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

    /**
     *删除主题后，需要发给客户的数据，如果没有，可以不传
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *删除主题后，需要发给客户的数据，如果没有，可以不传
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

