<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdCountReq.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，获取网关中的主题包含的连接数
 *
 * Generated from protobuf message <code>netsvr.topicUniqIdCountReq.TopicUniqIdCountReq</code>
 */
class TopicUniqIdCountReq extends \Google\Protobuf\Internal\Message
{
    /**
     *目标主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     */
    private $topics;
    /**
     *是否返回全部主题的连接数，如果设置为true，则网关会忽略topics字段的值，直接统计网关中每个主题的连接数
     *
     * Generated from protobuf field <code>bool countAll = 2;</code>
     */
    protected $countAll = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $topics
     *          目标主题
     *     @type bool $countAll
     *          是否返回全部主题的连接数，如果设置为true，则网关会忽略topics字段的值，直接统计网关中每个主题的连接数
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\TopicUniqIdCountReq::initOnce();
        parent::__construct($data);
    }

    /**
     *目标主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     *目标主题
     *
     * Generated from protobuf field <code>repeated string topics = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->topics = $arr;

        return $this;
    }

    /**
     *是否返回全部主题的连接数，如果设置为true，则网关会忽略topics字段的值，直接统计网关中每个主题的连接数
     *
     * Generated from protobuf field <code>bool countAll = 2;</code>
     * @return bool
     */
    public function getCountAll()
    {
        return $this->countAll;
    }

    /**
     *是否返回全部主题的连接数，如果设置为true，则网关会忽略topics字段的值，直接统计网关中每个主题的连接数
     *
     * Generated from protobuf field <code>bool countAll = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCountAll($var)
    {
        GPBUtil::checkBool($var);
        $this->countAll = $var;

        return $this;
    }

}

