<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uniqIdListResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，返回网关中全部的uniqId
 *
 * Generated from protobuf message <code>netsvr.uniqIdListResp.UniqIdListResp</code>
 */
class UniqIdListResp extends \Google\Protobuf\Internal\Message
{
    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     */
    protected $serverId = 0;
    /**
     *网关包含的uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 2;</code>
     */
    private $uniqIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $serverId
     *          网关唯一编号
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $uniqIds
     *          网关包含的uniqId
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\UniqIdListResp::initOnce();
        parent::__construct($data);
    }

    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     * @return int
     */
    public function getServerId()
    {
        return $this->serverId;
    }

    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverId = $var;

        return $this;
    }

    /**
     *网关包含的uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqIds()
    {
        return $this->uniqIds;
    }

    /**
     *网关包含的uniqId
     *
     * Generated from protobuf field <code>repeated string uniqIds = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uniqIds = $arr;

        return $this;
    }

}

