<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uniqIdCountResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *worker响应business，返回网关中uniqId的数量
 *
 * Generated from protobuf message <code>netsvr.uniqIdCountResp.UniqIdCountResp</code>
 */
class UniqIdCountResp extends \Google\Protobuf\Internal\Message
{
    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     */
    protected $serverId = 0;
    /**
     *网关中uniqId的数量
     *
     * Generated from protobuf field <code>int32 count = 2;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $serverId
     *          网关唯一编号
     *     @type int $count
     *          网关中uniqId的数量
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\UniqIdCountResp::initOnce();
        parent::__construct($data);
    }

    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     * @return int
     */
    public function getServerId()
    {
        return $this->serverId;
    }

    /**
     *网关唯一编号
     *
     * Generated from protobuf field <code>int32 serverId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverId = $var;

        return $this;
    }

    /**
     *网关中uniqId的数量
     *
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *网关中uniqId的数量
     *
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

