<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unRegisterReq.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，取消一个已经被注册的连接
 *
 * Generated from protobuf message <code>netsvr.unRegisterReq.UnRegisterReq</code>
 */
class UnRegisterReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 workerId = 1;</code>
     */
    protected $workerId = 0;
    /**
     * Generated from protobuf field <code>string registerId = 2;</code>
     */
    protected $registerId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $workerId
     *     @type string $registerId
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\UnRegisterReq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 workerId = 1;</code>
     * @return int
     */
    public function getWorkerId()
    {
        return $this->workerId;
    }

    /**
     * Generated from protobuf field <code>int32 workerId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setWorkerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->workerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string registerId = 2;</code>
     * @return string
     */
    public function getRegisterId()
    {
        return $this->registerId;
    }

    /**
     * Generated from protobuf field <code>string registerId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRegisterId($var)
    {
        GPBUtil::checkString($var, True);
        $this->registerId = $var;

        return $this;
    }

}

