<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unRegisterResp.proto

namespace Netsvr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *business向worker请求，worker响应取消注册的结果
 *
 * Generated from protobuf message <code>netsvr.unRegisterResp.UnRegisterResp</code>
 */
class UnRegisterResp extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Netsvr\GPBMetadata\UnRegisterResp::initOnce();
        parent::__construct($data);
    }

}

