<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkOnlineReq.proto

namespace Netsvr\GPBMetadata;

class CheckOnlineReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
checkOnlineReq.protonetsvr.checkOnlineReq"!
CheckOnlineReq
uniqIds (	B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

