<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoReq.proto

namespace Netsvr\GPBMetadata;

class ConnInfoReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
x
connInfoReq.protonetsvr.connInfoReq"
ConnInfoReq
uniqIds (	B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

