<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoUpdate.proto

namespace Netsvr\GPBMetadata;

class ConnInfoUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
é
connInfoUpdate.protonetsvr.connInfoUpdate"ˆ
ConnInfoUpdate
uniqId (	
	newUniqId (	
dataAsNewUniqIdExisted (

newSession (	
	newTopics (	
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

