<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoResp.proto

namespace Netsvr\GPBMetadata;

class ConnInfoResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
²
connInfoResp.protonetsvr.connInfoResp" 
ConnInfoResp;
items (2,.netsvr.connInfoResp.ConnInfoResp.ItemsEntryS

ItemsEntry
key (	4
value (2%.netsvr.connInfoResp.ConnInfoRespItem:8"3
ConnInfoRespItem
session (	
topics (	B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

