<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpenCustomUniqIdTokenResp.proto

namespace Netsvr\GPBMetadata;

class ConnOpenCustomUniqIdTokenResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¼
#connOpenCustomUniqIdTokenResp.proto$netsvr.connOpenCustomUniqIdTokenResp">
ConnOpenCustomUniqIdTokenResp
uniqId (	
token (	B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

