<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoDelete.proto

namespace Netsvr\GPBMetadata;

class ConnInfoDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ç
connInfoDelete.protonetsvr.connInfoDelete"g
ConnInfoDelete
uniqId (	
	delUniqId (

delSession (
delTopic (
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

