<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forceOfflineByCustomerId.proto

namespace Netsvr\GPBMetadata;

class ForceOfflineByCustomerId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
±
forceOfflineByCustomerId.protonetsvr.forceOfflineByCustomerId"=
ForceOfflineByCustomerId
customerIds (	
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

