<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forceOfflineGuest.proto

namespace Netsvr\GPBMetadata;

class ForceOfflineGuest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
§
forceOfflineGuest.protonetsvr.forceOfflineGuest"A
ForceOfflineGuest
uniqIds (	
delay (
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

