<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forceOffline.proto

namespace Netsvr\GPBMetadata;

class ForceOffline
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‰
forceOffline.protonetsvr.forceOffline"-
ForceOffline
uniqIds (	
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

