<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infoReq.proto

namespace Netsvr\GPBMetadata;

class InfoReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
è
infoReq.protonetsvr.infoReq"=
InfoReq
	routerCmd (
ctxData (
uniqId (	B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

