<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace Netsvr\GPBMetadata;

class LimitResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
limitResp.protonetsvr.limitResp"M
	LimitResp
serverId (.
items (2.netsvr.limitResp.LimitRespItem"E
LimitRespItem
name (	
concurrency (
	workerIds (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

