<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitReq.proto

namespace Netsvr\GPBMetadata;

class LimitReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
limitReq.protonetsvr.limitReq"-
LimitReq
onOpen (
	onMessage (B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

