<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitReq.proto

namespace Netsvr\GPBMetadata;

class LimitReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¼
limitReq.protonetsvr.limitReq"8
LimitReq,
items (2.netsvr.limitReq.LimitReqItem".
LimitReqItem
	workerIds (
num (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

