<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricsResp.proto

namespace Netsvr\GPBMetadata;

class MetricsResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
º
metricsResp.protonetsvr.metricsResp"®
MetricsResp
ctxData (9
items (2*.netsvr.metricsResp.MetricsResp.ItemsEntryS

ItemsEntry
key (4
value (2%.netsvr.metricsResp.MetricsStatusResp:8"®
MetricsStatusResp
count (
meanRate (
meanRateMax (
rate1 (
rate1Max (
rate5 (
rate5Max (
rate15 (
	rate15Max	 (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

