<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricsReq.proto

namespace Netsvr\GPBMetadata;

class MetricsReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ˆ
metricsReq.protonetsvr.metricsReq"0

MetricsReq
	routerCmd (
ctxData (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

