<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registerResp.proto

namespace Netsvr\GPBMetadata;

class RegisterResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‰
registerResp.protonetsvr.registerResp"-
RegisterResp
code (
message (	B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

