<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registerReq.proto

namespace Netsvr\GPBMetadata;

class RegisterReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
«
registerReq.protonetsvr.registerReq"Q
RegisterReq
workerId (
processCmdGoroutineNum (
serverId (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

