<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCast.proto

namespace Netsvr\GPBMetadata;

class SingleCast
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Â
singleCast.protonetsvr.singleCast"*

SingleCast
uniqId (	
data (">
SingleCastBulk,
items (2.netsvr.singleCast.SingleCastB\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

