<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicListResp.proto

namespace Netsvr\GPBMetadata;

class TopicListResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
è
topicListResp.protonetsvr.topicListResp"1
TopicListResp
serverId (
topics (	B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

