<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdListReq.proto

namespace Netsvr\GPBMetadata;

class TopicUniqIdListReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¯
topicUniqIdListReq.protonetsvr.topicUniqIdListReq"G
TopicUniqIdListReq
	routerCmd (
ctxData (
topic (	B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

