<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdCountReq.proto

namespace Netsvr\GPBMetadata;

class TopicUniqIdCountReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
topicUniqIdCountReq.protonetsvr.topicUniqIdCountReq"[
TopicUniqIdCountReq
	routerCmd (
ctxData (
topics (	
countAll (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

