<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUnsubscribe.proto

namespace Netsvr\GPBMetadata;

class TopicUnsubscribe
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¤
topicUnsubscribe.protonetsvr.topicUnsubscribe"@
TopicUnsubscribe
uniqId (	
topics (	
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

