<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCountReq.proto

namespace Netsvr\GPBMetadata;

class TopicCountReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‘
topicCountReq.protonetsvr.topicCountReq"3
TopicCountReq
	routerCmd (
ctxData (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

