<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicSubscribe.proto

namespace Netsvr\GPBMetadata;

class TopicSubscribe
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ž
topicSubscribe.protonetsvr.topicSubscribe">
TopicSubscribe
uniqId (	
topics (	
data (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

