<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdListResp.proto

namespace Netsvr\GPBMetadata;

class TopicCustomerIdListResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
þ
topicCustomerIdListResp.protonetsvr.topicCustomerIdListResp"×
TopicCustomerIdListRespQ
items (2B.netsvr.topicCustomerIdListResp.TopicCustomerIdListResp.ItemsEntryi

ItemsEntry
key (	J
value (2;.netsvr.topicCustomerIdListResp.TopicCustomerIdListRespItem:8"2
TopicCustomerIdListRespItem
customerIds (	B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

