<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCountResp.proto

namespace Netsvr\GPBMetadata;

class TopicCountResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
topicCountResp.protonetsvr.topicCountResp"0
TopicCountResp
ctxData (
count (B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

