<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdCountResp.proto

namespace Netsvr\GPBMetadata;

class TopicUniqIdCountResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
è
topicUniqIdCountResp.protonetsvr.topicUniqIdCountResp"¢
TopicUniqIdCountResp
ctxData (K
items (2<.netsvr.topicUniqIdCountResp.TopicUniqIdCountResp.ItemsEntry,

ItemsEntry
key (	
value (:8B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

