<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCountResp.proto

namespace Netsvr\GPBMetadata;

class TopicCountResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‘
topicCountResp.protonetsvr.topicCountResp"1
TopicCountResp
serverId (
count (B\'Znetsvr/ÊNetsvrâNetsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

