<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uniqIdListResp.proto

namespace Netsvr\GPBMetadata;

class UniqIdListResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
uniqIdListResp.protonetsvr.uniqIdListResp"!
UniqIdListResp
uniqIds (	B\'Znetsvr/ Netsvr‚Netsvr\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

