<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkOnlineResp.proto

namespace NetsvrProtocol\GPBMetadata;

class CheckOnlineResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
œ
checkOnlineResp.protonetsvr.checkOnlineResp""
CheckOnlineResp
uniqIds (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

