<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpen.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnOpen
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
é
connOpen.protonetsvr.connOpen"}
ConnOpen
uniqId (	
rawQuery (	
subProtocol (	
xForwardedFor (	
xRealIp (	

remoteAddr (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

