<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoReq.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnInfoReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Í
connInfoReq.protonetsvr.connInfoReq"[
ConnInfoReq
uniqIds (	

reqSession (
reqCustomerId (
reqTopic (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

