<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoUpdate.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnInfoUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ä
connInfoUpdate.protonetsvr.connInfoUpdate"l
ConnInfoUpdate
uniqId (	

newSession (	
newCustomerId (	
	newTopics (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

