<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoByCustomerIdResp.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnInfoByCustomerIdResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ª
connInfoByCustomerIdResp.protonetsvr.connInfoByCustomerIdResp"Ý
ConnInfoByCustomerIdRespS
items (2D.netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdResp.ItemsEntryl

ItemsEntry
key (	M
value (2>.netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItems:8"m
ConnInfoByCustomerIdRespItemsL
items (2=.netsvr.connInfoByCustomerIdResp.ConnInfoByCustomerIdRespItem"O
ConnInfoByCustomerIdRespItem
session (	
uniqId (	
topics (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

