<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connClose.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnClose
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¾
connClose.protonetsvr.connClose"P
	ConnClose
uniqId (	

customerId (	
session (	
topics (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

