<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connOpenResp.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnOpenResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ý
connOpenResp.protonetsvr.connOpenResp"i
ConnOpenResp
allow (

newSession (	
newCustomerId (	
	newTopics (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

