<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connInfoByCustomerIdReq.proto

namespace NetsvrProtocol\GPBMetadata;

class ConnInfoByCustomerIdReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ñ
connInfoByCustomerIdReq.protonetsvr.connInfoByCustomerIdReq"g
ConnInfoByCustomerIdReq
customerIds (	

reqSession (
	reqUniqId (
reqTopic (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

