<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customerIdCountResp.proto

namespace NetsvrProtocol\GPBMetadata;

class CustomerIdCountResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¦
customerIdCountResp.protonetsvr.customerIdCountResp"$
CustomerIdCountResp
count (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

