<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limitResp.proto

namespace NetsvrProtocol\GPBMetadata;

class LimitResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
œ
limitResp.protonetsvr.limitResp".
	LimitResp
onOpen (
	onMessage (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

