<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registerReq.proto

namespace NetsvrProtocol\GPBMetadata;

class RegisterReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¯
registerReq.protonetsvr.registerReq"=
RegisterReq
events (
processCmdGoroutineNum (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

