<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastBulkByCustomerId.proto

namespace NetsvrProtocol\GPBMetadata;

class SingleCastBulkByCustomerId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ï
 singleCastBulkByCustomerId.proto!netsvr.singleCastBulkByCustomerId"?
SingleCastBulkByCustomerId
customerIds (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

