<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCast.proto

namespace NetsvrProtocol\GPBMetadata;

class SingleCast
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
š
singleCast.protonetsvr.singleCast"*

SingleCast
uniqId (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

