<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastByCustomerId.proto

namespace NetsvrProtocol\GPBMetadata;

class SingleCastByCustomerId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Â
singleCastByCustomerId.protonetsvr.singleCastByCustomerId":
SingleCastByCustomerId

customerId (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

