<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: singleCastBulk.proto

namespace NetsvrProtocol\GPBMetadata;

class SingleCastBulk
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
§
singleCastBulk.protonetsvr.singleCastBulk"/
SingleCastBulk
uniqIds (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

