<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdToUniqIdsListReq.proto

namespace NetsvrProtocol\GPBMetadata;

class TopicCustomerIdToUniqIdsListReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ë
%topicCustomerIdToUniqIdsListReq.proto&netsvr.topicCustomerIdToUniqIdsListReq"1
TopicCustomerIdToUniqIdsListReq
topics (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

