<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdCountReq.proto

namespace NetsvrProtocol\GPBMetadata;

class TopicCustomerIdCountReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
topicCustomerIdCountReq.protonetsvr.topicCustomerIdCountReq";
TopicCustomerIdCountReq
topics (	
countAll (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

