<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdListResp.proto

namespace NetsvrProtocol\GPBMetadata;

class TopicUniqIdListResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ò
topicUniqIdListResp.protonetsvr.topicUniqIdListResp"Ã
TopicUniqIdListRespI
items (2:.netsvr.topicUniqIdListResp.TopicUniqIdListResp.ItemsEntrya

ItemsEntry
key (	B
value (23.netsvr.topicUniqIdListResp.TopicUniqIdListRespItem:8"*
TopicUniqIdListRespItem
uniqIds (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

