<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicPublishBulk.proto

namespace NetsvrProtocol\GPBMetadata;

class TopicPublishBulk
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¬
topicPublishBulk.protonetsvr.topicPublishBulk"0
TopicPublishBulk
topics (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

