<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicCustomerIdCountResp.proto

namespace NetsvrProtocol\GPBMetadata;

class TopicCustomerIdCountResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
™
topicCustomerIdCountResp.protonetsvr.topicCustomerIdCountResp"ù
TopicCustomerIdCountRespS
items (2D.netsvr.topicCustomerIdCountResp.TopicCustomerIdCountResp.ItemsEntry,

ItemsEntry
key (	
value (:8B?ZnetsvrProtocol/ NetsvrProtocol‚NetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

