<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicUniqIdCountReq.proto

namespace NetsvrProtocol\GPBMetadata;

class TopicUniqIdCountReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¹
topicUniqIdCountReq.protonetsvr.topicUniqIdCountReq"7
TopicUniqIdCountReq
topics (	
countAll (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

