<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto

namespace NetsvrProtocol\GPBMetadata;

class Transfer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
É
transfer.protonetsvr.transfer"]
Transfer
uniqId (	

customerId (	
session (	
topics (	
data (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

