<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uniqIdCountResp.proto

namespace NetsvrProtocol\GPBMetadata;

class UniqIdCountResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
š
uniqIdCountResp.protonetsvr.uniqIdCountResp" 
UniqIdCountResp
count (B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

