<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unRegisterReq.proto

namespace NetsvrProtocol\GPBMetadata;

class UnRegisterReq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
•
unRegisterReq.protonetsvr.unRegisterReq"
UnRegisterReq
connId (	B?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

