<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unRegisterResp.proto

namespace NetsvrProtocol\GPBMetadata;

class UnRegisterResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ˆ
unRegisterResp.protonetsvr.unRegisterResp"
UnRegisterRespB?ZnetsvrProtocol/ÊNetsvrProtocolâNetsvrProtocol\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

